### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by kimmobrunfeldt** [achiku/planter#13]
Hi, thanks for the great tool. I made a docker file which packages planter and plantuml in one docker image: https://github.com/kimmobrunfeldt/planter-docker. This makes using the tool a one-liner assuming docker is installed.

It exposes planter and plantuml directly, but also implements `er` command which allows selecting tables with a matching pattern. Useful for databases with tens or hundreds of tables.

**Comment by achiku** [comment]
@kimmobrunfeldt 

Hi, that's awesome! Yeah, installing plantuml is quite a task, and your docker image looks really handy for quick start :) Can I add a link to your repo in README?

**Comment by kimmobrunfeldt** [comment]
@achiku sure! Go ahead :+1: Can't make guarantees of the maintenance but should be able to merge PRs.
