### ISSUE TITLE
Partitions are included as entities (should skip)

### ISSUE THREAD

**Issue by thkerkmann-rwe** [achiku/planter#32]
Partitions of a table are included as entities.
This can result in extremly long output, repeating the same entity with a new name (partition name) again and again.

Can partitions be skipped please.

**Comment by thkerkmann-rwe** [comment]
I see there is already a [pull-request](https://github.com/achiku/planter/pull/26) for that. Tested it locally for myself, very nice, works as expected. Thanks to @skissane

**Comment by achiku** [comment]
Thank you for pointing out! p-r is merged!
